### ISSUE TITLE
Documentation Error: optimise vs optimize

### ISSUE THREAD

**Issue by cferdinandi** [prateekbh/gulp-optimize-js#3]
Hey there - thanks for putting this together! I noticed a small typo under the Usage instructions:

``` js
var optimisejs = require('gulp-optimise-js');

gulp.task('optimize', function() {
  gulp.src('./js/minified.js')
    .pipe(optimisejs())
    .pipe(gulp.dest('./dist/'))
});
```

optimi**s**e should be optimi**z**e, based on what gets installed from NPM:

``` js
var optimizejs = require('gulp-optimize-js');

gulp.task('optimize', function() {
  gulp.src('./js/minified.js')
    .pipe(optimizejs())
    .pipe(gulp.dest('./dist/'))
});
```

In its current form, this error is thrown:

```
Error: Cannot find module 'gulp-optimise-js'
```

I'm happy to issue a PR for this if you'd like. Let me know.

**Comment by prateekbh** [comment]
@cferdinandi sure go ahead, send the PR 👍

**Comment by cferdinandi** [comment]
I notice you took care of this already. Thanks!

**Comment by cferdinandi** [comment]
This update does not seem to have made its way to the NPM readme: https://www.npmjs.com/package/gulp-optimize-js

**Comment by prateekbh** [comment]
@cferdinandi done now :)
